
FROM custom_ollama_base


WORKDIR /app


COPY requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/

EXPOSE 8100


CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8100"]
